# Generated by Django 2.1.4 on 2021-08-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Emp', '0001_initial'),
        ('TestModel', '0002_teacher_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=200)),
                ('emp', models.ManyToManyField(to='Emp.Emp')),
                ('teacher', models.ManyToManyField(to='TestModel.Teacher')),
            ],
        ),
    ]
