# Generated by Django 2.1.4 on 2021-08-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=45)),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.Teacher')),
            ],
        ),
    ]
