# Generated by Django 3.2.6 on 2021-08-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_teacher_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
