# Generated by Django 3.2.6 on 2021-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
