# Generated by Django 2.1.4 on 2021-08-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('demoName', models.CharField(max_length=45)),
                ('demoUrl', models.CharField(max_length=400)),
            ],
        ),
    ]
