# Generated by Django 2.1.4 on 2021-08-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='DemoList',
        ),
    ]
