# Generated by Django 3.2.6 on 2021-08-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0002_auto_20210816_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demolist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
